name: Release tulo.SignPdf

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  call-release:
    uses: ./.github/workflows/common-release.yml
    with:
      project_name: Tulo.SignPdf
      project_path: Src/Tulo.SigningPdf/Tulo.SigningPdf.csproj
      publish_dir: publish/Tulo.SigningPdf
      zip_prefix: Tulo.SignPdf
      executable_name: Tulo.SigningPdf.exe
      runtime: win-x64
      dotnet_version: 8.0.x
      config_file: nuget.config
      prerelease: false